### ISSUE TITLE
Translate title to Japanese

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/japanese#25]
FYI: You can change the title of the [DLang Tour](http://tour.dlang.org/tour/ja) to Japanese at the main [`index.yml`](https://github.com/dlang-tour/japanese/blob/master/index.yml) file if you want to. The menu titles can be changed in their respective `index.yml` of the according folder.

**Comment by WebFreak001** [comment]
If you mean the button in the top left, it is translated, also in the german translation, it simply ignores the title there.

https://github.com/dlang-tour/dlang-tour/blob/c17a351073b0700990af470ec55769c5da0eb6cb/views/base.dt#L23

**Comment by wilzbach** [comment]
@WebFreak001 Oh yeah - that's a bug..
Btw you might also be interested in this PR https://github.com/dlang-tour/dlang-tour/pull/510 (it implements a simple translation module for the Dlang Tour).

**Comment by simdnyan** [comment]
We go as is.
